###################
#+++++++++++++++++#
#+  CGMPX Config +#
#+++++++++++++++++#
###################

AFKSettings:
    # AFKまでの時間を設定(秒)
    AFKTime: 300

    # AFKMassage %Player% でプレイヤー名を代入
    AFKMessage: "%Player% &eは離席中です。"
    BackMessage: "%Player% &eが離席から戻りました。"

    # AFK時にダメージを受けないようにするか
    EnableGodMode: true

    # AFK時に押せないようにするか(無効化中)
    EnableAntiPush: false